apiVersion: apps/v1
kind: Deployment
metadata:
  name: distributed-task-scheduler
spec:
  replicas: 4
  selector:
    matchLabels:
      app: distributed-task-scheduler
  template:
    metadata:
      labels:
        app: distributed-task-scheduler
    spec:
      containers:
        - name: distributed-task-scheduler
          image: distributed-task-scheduler:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
