apiVersion: v1
kind: Service
metadata:
  name: distributed-task-scheduler-service
spec:
  type: NodePort
  selector:
    app: distributed-task-scheduler
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30036
